{{- if .Values.networkPolicies.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "eventrouter-app.name" . }}-network-policy
  labels:
    {{- include "eventrouter-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eventrouter-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.kubernetesEndpointCIDR }}
    ports:
    - protocol: TCP
      port: 443
  policyTypes:
  - Egress
  - Ingress
{{- end }}
