apiVersion: v1
data:
  config.json: |- 
    {
      "sink": "stdout"
    }
kind: ConfigMap
metadata:
  name: {{ include "eventrouter-app.name" . }}-values
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eventrouter-app.labels" . | nindent 4 }}
