apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "eventrouter-app.fullname" . }}-psp
  labels:
    {{- include "eventrouter-app.labels" . | nindent 4 }}
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    ranges:
    - max: 65535
      min: 1000
    rule: MustRunAs
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - secret
  - configMap
