apiVersion: v1
appVersion: v0.3
description: "Heptio Event Router: A simple introspective kubernetes service that forwards events to a specified sink."
home: https://github.com/heptiolabs/eventrouter
name: eventrouter-app
maintainers:
- name: Heptio/VMWare
  url: https://github.com/heptiolabs/eventrouter
- name: Giant Swarm applications team
  url: https://github.com/giantswarm/eventrouter-app
sources:
- https://github.com/heptiolabs/eventrouter
- https://github.com/giantswarm/eventrouter-app
version: [[ .Version ]]