# Default values for eventrouter-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/giantswarm/eventrouter
  tag: v0.3-giantswarm
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

networkPolicies:
  # when  enabled, it will create default deny-all policy together with an app  specific policy
  # kubernetes endpoint is required then
  enabled: falses
  # provide 'kubectl get endpoints kubernetes' CIDR e.g. 10.158.0.5/32
  kubernetesEndpointCidr: ''
